config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'signup/select' , to: 'signups#select'
  get 'signup/tel' , to: 'signups#tel'
  get 'signup/address' , to: 'signups#address'
  get 'signup/pay' , to: 'signups#pay'
  get 'signup/finish' , to: 'signups#finish'
  get '/logout', to: 'logout#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :users, only: [:show, :new]
  resources :top, only: [:index]
  resources :items, only: [:new, :create, :show, :update, :destroy]
  resources :purchases, only: [:index]
  resources :users, only: [:index]
  resources :cards, only: [:index, :new] do
    collection do
      get 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :items do
    member do
      get :confirmation
      patch :confirmed
    end
  end
  resources :profile, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  # アソシエーション
  has_many :items
  has_many :sns_credentials, dependent: :destroy
  has_one :user_detail
  has_one :card
  
  # バリデーション
  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,                presence: true, length: {minimum: 6}
  # validates :password_confirmation,   presence: true, length: {minimum: 6}
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  def self.from_auth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  def callback_for(provider)
    @user = User.from_auth(request.env["omniauth.auth"])
    if @user.present?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to new_user_session_path and return
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout "compact"
  # GET /resource/sign_up
  # def new

  # end

  # def show

  # end
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  layout  "compact"

  # GET /resource/sign_in
  # def new
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new]
  layout "tab", only: [:show, :new]

  def new
  end

  def show
  end
end

app/views/users/_info_todo.html.haml
.mypage__main__menu
  %ul.mypage__main__menu__tabs
    %input#info_tab{checked: "checked", name: "mypage__main__menu__tabs__name", type: "radio"}/
    %label.mypage__main__menu__tabs__name{for: "info_tab"}
      %li お知らせ

    %input#todo_tab{name: "mypage__main__menu__tabs__name", type: "radio"}/
    %label.mypage__main__menu__tabs__name{for: "todo_tab"}
      %li やることリスト

    #info__contents.mypage__main__menu__tabs__contents
      %ul.mypage__main__menu__tabs__contents__info_lists
        %li.mypage__main__menu__tabs__contents__info_lists__body
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__body__link' do
            %figure
              =image_tag "//static.mercdn.net/images/mercari_profile.png", class: "mypage__main__menu__tabs__contents__info_lists__body__link__icon", width:"48px", height:"48px"
            .mypage__main__menu__tabs__contents__info_lists__body__link__box
              .mypage__main__menu__tabs__contents__info_lists__body__link__box__text
                テキスト1
              %time.mypage__main__menu__tabs__contents__info_lists__body__link__box__time
                %i.far.fa-clock
                %span 1日前
          %i.fa.fa-angle-right.fa-2x
        %li.mypage__main__menu__tabs__contents__info_lists__body
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__body__link' do
            %figure
              =image_tag "//static.mercdn.net/images/mercari_profile.png", class: "mypage__main__menu__tabs__contents__info_lists__body__link__icon", width:"48px", height:"48px"
            .mypage__main__menu__tabs__contents__info_lists__body__link__box
              .mypage__main__menu__tabs__contents__info_lists__body__link__box__text
                テキスト2
              %time.mypage__main__menu__tabs__contents__info_lists__body__link__box__time
                %i.far.fa-clock
                %span 2日前
          %i.fa.fa-angle-right.fa-2x
        %li.mypage__main__menu__tabs__contents__info_lists__body
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__body__link' do
            %figure
              =image_tag "//static.mercdn.net/images/mercari_profile.png", class: "mypage__main__menu__tabs__contents__info_lists__body__link__icon", width:"48px", height:"48px"
            .mypage__main__menu__tabs__contents__info_lists__body__link__box
              .mypage__main__menu__tabs__contents__info_lists__body__link__box__text
                テキスト3
              %time.mypage__main__menu__tabs__contents__info_lists__body__link__box__time
                %i.far.fa-clock
                %span 3日前
          %i.fa.fa-angle-right.fa-2x
        %li.mypage__main__menu__tabs__contents__info_lists__body
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__body__link' do
            %figure
              =image_tag "//static.mercdn.net/images/mercari_profile.png", class: "mypage__main__menu__tabs__contents__info_lists__body__link__icon", width:"48px", height:"48px"
            .mypage__main__menu__tabs__contents__info_lists__body__link__box
              .mypage__main__menu__tabs__contents__info_lists__body__link__box__text
                テキスト4
              %time.mypage__main__menu__tabs__contents__info_lists__body__link__box__time
                %i.far.fa-clock
                %span 4日前
          %i.fa.fa-angle-right.fa-2x
        %li.mypage__main__menu__tabs__contents__info_lists__body
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__body__link' do
            %figure
              =image_tag "//static.mercdn.net/images/mercari_profile.png", class: "mypage__main__menu__tabs__contents__info_lists__body__link__icon", width:"48px", height:"48px"
            .mypage__main__menu__tabs__contents__info_lists__body__link__box
              .mypage__main__menu__tabs__contents__info_lists__body__link__box__text
                テキスト5
              %time.mypage__main__menu__tabs__contents__info_lists__body__link__box__time
                %i.fa.far-clock
                %span 5日前
          %i.fa.fa-angle-right.fa-2x

        .mypage__main__menu__tabs__contents__info_lists__view
          = link_to "#", class: 'mypage__main__menu__tabs__contents__info_lists__view__link' do
            一覧を見る

    #todo__contents.mypage__main__menu__tabs__contents
      .mypage__main__menu__tabs__contents__todo_lists
        %ul.mypage__main__menu__tabs__contents__todo_lists__body
          =image_tag "mercari_icon_white.png", class: "mypage__main__menu__tabs__contents__todo_lists__body__icon", width:"700px", height:"160px"
          %li 現在、やることリストはありません

app/views/users/_purchased.html.haml
.mypage__main__purchased_product
  %h2.mypage__main__purchased_product__title
    購入した商品
  %ul.mypage__main__purchased_product__tabs
    %input#trading_tab{checked: "checked", name: "tab_purchased", type: "radio"}/
    %label.mypage__main__purchased_product__tabs__name{for: "trading_tab"}
      %li 取引中
    %input#transactions_tab{name: "tab_purchased", type: "radio"}/
    %label.mypage__main__purchased_product__tabs__name{for: "transactions_tab"}
      %li 過去の取引

    #trading__contents.mypage__main__purchased_product__tabs__contents
      %ul.mypage__main__purchased_product__tabs__contents__trading_lists
        .mypage__main__purchased_product__tabs__contents__trading_lists__body
          =image_tag "mercari_icon_white.png", class: "mypage__main__menu__tabs__contents__trading_lists__body__icon", width:"700px", height:"160px"
          %li 取引中の商品がありません
    #transactions__contents.mypage__main__purchased_product__tabs__contents
      %ul.mypage__main__purchased_product__tabs__contents__transactions_lists
        .mypage__main__purchased_product__tabs__contents__transactions_lists__body
          =image_tag "mercari_icon_white.png", class: "mypage__main__menu__tabs__contents__transactions_lists__body__icon", width:"700px", height:"160px"
          %li 過去に取引した商品がありません

app/views/users/_side_menu.html.haml
.mypage__side_menu
  %ul.mypage__side_menu__lists
    - if (controller_path == 'users' && action_name == 'show')
      %li#select.mypage__side_menu__lists__name    
        = link_to user_path(id: current_user.id), class: 'mypage__side_menu__lists__name__text', id: "show" do
          マイページ
          %i.fa.fa-angle-right.fa-2x
    - else
      %li.mypage__side_menu__lists__name
        = link_to user_path(id: current_user.id), class: 'mypage__side_menu__lists__name__text', id: "show" do
          マイページ
          %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        お知らせ
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        やることリスト
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        いいね！一覧
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        出品する
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        出品した商品 - 出品中
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        出品した商品 - 取引中
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        出品した商品 - 売却済み
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        購入した商品 - 取引中
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        購入した商品 - 過去の取引
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        ニュース一覧
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        評価一覧
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        ガイド
        %i.fa.fa-angle-right.fa-2x
    %li.mypage__side_menu__lists__name
      = link_to "#", class: 'mypage__side_menu__lists__name__text' do
        お問い合わせ
        %i.fa.fa-angle-right.fa-2x
        
  %ul.mypage__side_menu__merupay
    .mypage__side_menu__merupay__title
      メルペイ
    .mypage__side_menu__merupay__lists
      %li.mypage__side_menu__merupay__lists__name
        = link_to "#", class: 'mypage__side_menu__merupay__lists__name__text' do
          売上・振込申請
          %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__merupay__lists__name
        = link_to "#", class: 'mypage__side_menu__merupay__lists__name__text' do
          ポイント
          %i.fa.fa-angle-right.fa-2x

  %ul.mypage__side_menu__setting
    .mypage__side_menu__setting__title
      設定
    .mypage__side_menu__setting__lists
      %li.mypage__side_menu__setting__lists__name
        = link_to profile_index_path, class: 'mypage__side_menu__setting__lists__name__text' do
          プロフィール
          %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__setting__lists__name
        = link_to "#", class: 'mypage__side_menu__setting__lists__name__text' do
          発送元・お届け先住所変更
          %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__setting__lists__name
        = link_to "/cards", class: 'mypage__side_menu__setting__lists__name__text' do
          支払い方法
          %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__setting__lists__name
        = link_to "#", class: 'mypage__side_menu__setting__lists__name__text' do
          メール/パスワード
          %i.fa.fa-angle-right.fa-2x
      - if (controller_path == 'users' && action_name == 'new')
        %li#select.mypage__side_menu__setting__lists__name
          = link_to new_user_path, class: 'mypage__side_menu__setting__lists__name__text', id: "new" do
            本人情報
            %i.fa.fa-angle-right.fa-2x
      - else
        %li.mypage__side_menu__setting__lists__name
          = link_to new_user_path, class: 'mypage__side_menu__setting__lists__name__text', id: "new" do
            本人情報
            %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__setting__lists__name
        = link_to "#", class: 'mypage__side_menu__setting__lists__name__text' do
          電話番号の確認
          %i.fa.fa-angle-right.fa-2x
      %li.mypage__side_menu__setting__lists__name
        = link_to logout_path, class: 'mypage__side_menu__setting__lists__name__text' do
          ログアウト
          %i.fa.fa-angle-right.fa-2x

app/views/users/_user.html.haml
.mypage__main__user
  .mypage__main__user__container
    = link_to "#", class: 'mypage__main__user__container__link' do
      %figure.mypage__main__user__container__link__icon
        = image_tag "sample01.png", width:"60px", height:"60px"
      %h3.mypage__main__user__container__link__user_name
        = current_user.nickname
      .mypage__main__user__container__link__count
        .mypage__main__user__container__link__count__rate
          評価
          %span 5
        .mypage__main__user__container__link__count__exhibit
          出品数
          %span 2

app/views/users/new.html.haml
= render 'layouts/breadcrumbs'
.mypage
  .mypage__identification
    .mypage__identification__main
      %h2 本人情報の登録
      .mypage__identification__main__content
        .mypage__identification__main__content__info
          .mypage__identification__main__content__info__text
            お客さまの本人情報をご登録ください。<br>
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          .mypage__identification__main__content__info__link
            =link_to "#", class: 'mypage__identification__main__content__info__link__text' do
              本人確認書類のアップロードについて
              %i.fa.fa-angle-right
        .mypage__identification__main__content__name
          %label お名前<br>
          %p 栗村 佑紀
        .mypage__identification__main__content__kana
          %label お名前カナ<br>
          %p クリムラ ユウキ
        .mypage__identification__main__content__birth_day
          %label 生年月日<br>
          %p 1987/12/13
        .mypage__identification__main__content__fix
          %label 郵便番号
          %span 任意
          = text_area_tag :text, '', class: 'mypage__identification__main__content__fix__input', placeholder: '例）1234567'
        .mypage__identification__main__content__prefectures
          %label 都道府県
          %span 任意
          .mypage__identification__main__content__prefectures__select
            %i.fa.fa-angle-down.fa-2x
            -# サーバーサイド実装時インスタンス変数に変更
            = form_for :user, html: { class: "select" } do |f|
              = f.collection_select :area, Prefecture.all, :id, :name, {prompt: "--"}
        .mypage__identification__main__content__city
          %label 市区町村
          %span 任意
          = text_area_tag :text, '', class: 'mypage__identification__main__content__city__input', placeholder: '例) 横浜市緑区'
        .mypage__identification__main__content__address
          %label 番地 
          %span 任意
          = text_area_tag :text, '', class: 'mypage__identification__main__content__address__input', placeholder: '例) 青山1−1−1'
        .mypage__identification__main__content__buildding
          %label 建物名 
          %span 任意
          = text_area_tag :text, '', class: 'mypage__identification__main__content__buildding__input', placeholder: '例) 柳ビル103'
        .mypage__identification__main__content__btn
          %button 登録する
        .mypage__identification__main__content__description
          =link_to "#", class: "mypage__identification__main__content__description__text" do
            本人情報の登録について
            %i.fa.fa-angle-right
  =render partial: "users/side_menu"

app/views/users/show.html.haml
= render 'layouts/breadcrumbs'
.mypage
  .mypage__main
    =render partial: "users/user"
    =render partial: "users/info_todo"
    =render partial: "users/purchased"
  =render partial: "users/side_menu"