config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'signup/select' , to: 'signups#select'
  get 'signup/tel' , to: 'signups#tel'
  get 'signup/address' , to: 'signups#address'
  get 'signup/pay' , to: 'signups#pay'
  get 'signup/finish' , to: 'signups#finish'
  get '/logout', to: 'logout#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :users, only: [:show, :new]
  resources :top, only: [:index]
  resources :items, only: [:new, :create, :show, :update, :destroy]
  resources :purchases, only: [:index]
  resources :users, only: [:index]
  resources :cards, only: [:index, :new] do
    collection do
      get 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :items do
    member do
      get :confirmation
      patch :confirmed
    end
  end
  resources :profile, only: [:index]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many   :item_images, dependent: :destroy

  accepts_nested_attributes_for :item_images, allow_destroy: true

  validates :name,                       presence: true, length: {maximum: 40}
  validates :description,                presence: true, length: {maximum: 1000}
  validates :category_id,                numericality: {message: 'Please select'}
  validates :state,                      exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_charges,           exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_method,            exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_source_area,       exclusion: {in: %w(---), message: 'Please select'}
  validates :days_ship,                  exclusion: {in: %w(---), message: 'Please select'}
  validates :price,                      presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'payjp'

  before_action :authenticate_user!, only: [:new, :confirmation, :confirmed]
  before_action :set_item, only: [:destroy, :show, :confirmed, :confirmation]
  layout "compact", only: [:new, :edit, :confirmation]

  def new
    @item = Item.new
    @item_image = @item.item_images.build
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      params[:item_images]['image'].each do |i|
        @item.item_images.create!(image: i, item_id: @item.id)
      end
      redirect_to item_path(@item)
    else
      render :edit
    end
  end


  def show
    @user_items = Item.where(user_id: @item.user_id)
    @images = ItemImage.where(item_id: @user_items)
    @detail = @item.user.user_detail
 
    # if current_user.card.blank?
    #   redirect_to controller: 'cards', action: 'new'
    # else
    #   Payjp.api_key = Rails.application.credentials.payjp[:secret]
    #   customer = Payjp::Customer.retrieve(card.customer_id)
    #   @default_card_information = customer.cards.retrieve(card.card_id)
    # end
  end

  def confirmation
    card = Card.where(user_id: current_user.id).first
    @detail = UserDetail.find_by(user_id: @item.user_id)
    @img = ItemImage.find_by(item_id: @item.id)

    if current_user.card.blank?
      redirect_to controller: 'cards', action: 'new'
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
  
  def confirmed
    @item.update(status: 'Sold')
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = Rails.application.credentials.payjp[:secret]
    Payjp::Charge.create(
    amount: @item.price,
    customer: card.customer_id,
    currency: 'jpy',
    )
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      params[:item_images]['image'].each do |i|
        @item_image = @item.item_images.create!(image: i, item_id: @item.id)
      end
      redirect_to root_path
    end
  end

  def destroy
      if @item.user_id == current_user.id
        @item.destroy
        redirect_to root_path
      end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :state, :shipping_charges, :shipping_method, :shipping_source_area, :days_ship, :price, item_images_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.includes(:category, :user).find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%footer.sell-footer
  %nav
    %ul.clearfix
      %li
        = link_to 'プライバシーポリシー', '#'
      %li
        = link_to 'メルカリ利用規約', '#'
      %li
        = link_to '特定商取引に関する表記', '#'
  = link_to "#", class: "sell-footer__logo" do
    = image_tag 'footer-logo-gray.svg', alt: 'mercari', height: '65', width: '80'
  %p
    %small ©︎ 2019 team0706a

app/views/items/_form.html.haml
= form_for @item, html: { class: "sell-form" } do |f|
  .sell-content
    .form-group
      = f.label :name do
        商品名
        %span.form-require 必須
      %div
        = f.text_field :name, class: 'input-default input-default__width', placeholder: "商品名（必須 40文字まで)"
    .form-group
      = f.label :description do
        商品の説明
        %span.form-require 必須
      = f.text_area :description, class: 'textarea-default', size: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
  .sell-content.clearfix
    %h3.sub-head 商品の詳細
    .form-box
      .form-group
        = f.label :category_id do
          カテゴリー
          %span.form-require 必須
        %div
          .select-wrap
            = f.select :category_id, [["レディース", "1"], ["メンズ", "2"], ["ベビー・キッズ","3"], ["インテリア・住まい・小物","4"], ["本・音楽・ゲーム","5"], ["おもちゃ・ホビー・グッズ","6"], ["コスメ・香水・美容","7"], ["家電・スマホ・カメラ","8"], ["スポーツ・レジャー","9"], ["ハンドメイド","10"], ["チケット","11"], ["自転車・オートバイ","12"], ["その他", "13"]], {prompt: "---"}, {class: 'select-default'}
            %i.fa.fa-chevron-down.fa-lg
      .form-group
        = f.label :state do
          商品の状態
          %span.form-require 必須
        .select-wrap
          = f.select :state, [["新品・未使用", "新品・未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"],], {prompt: "---"}, {class: "select-default"}
          %i.fa.fa-chevron-down.fa-lg
  .sell-content.clearfix
    %h3.sub-head 配送について
    = link_to "#", class: "form-question" do
      %i.fa.fa-question-circle
    .form-box
      .form-group
        = f.label :shipping_charges do
          配送料の負担
          %span.form-require 必須
        %div
          .select-wrap
            = f.select :shipping_charges, [["送料込み(出品者負担)", "送料込み(出品者負担)"], ["着払い(購入者負担)", "着払い(購入者負担)"]], {prompt: "---"}, {class: 'select-default'}
            %i.fa.fa-chevron-down.fa-lg
      .form-group
        = f.label :shipping_method do
          配送の方法
          %span.form-require 必須
        %div
          .select-wrap
            = f.select :shipping_method, [["未定", "未定"], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便(定型、定形外)", "普通郵便(定型、定形外)"], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["クリックポスト", "クリックポスト"], ["ゆうパケット", "ゆうパケット"]], {prompt: "---"}, {class: 'select-default'}
            %i.fa.fa-chevron-down.fa-lg
      .form-group
        = f.label :shipping_source_area do
          発送元の地域
          %span.form-require 必須
        .select-wrap
          = f.collection_select :shipping_source_area, Prefecture.all, :id, :name, {prompt: "---"}, {class: 'select-default'}
          %i.fa.fa-chevron-down.fa-lg
      .form-group
        = f.label :days_ship do
          発送までの日数
          %span.form-require 必須
        .select-wrap
          = f.select :days_ship, [["1~2日で発送", "1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]], {prompt: "---"}, {class: 'select-default'}
          %i.fa.fa-chevron-down.fa-lg
  .sell-content.clearfix
    %h3.sub-head 販売価格(300〜9,999,999)
    = link_to "#", class: "form-question" do
      %i.fa.fa-question-circle
    .form-box
      %ul.price
        %li.form-group
          .clearfix
            = f.label :price, class: "l-left" do
              価格
              %span.form-require 必須
            .l-right.price-input
              ¥
              .price-input__container
                = f.text_field :price, class: 'input-default', id: 'item_price', placeholder: "例）300"
        %li.top_border.clearfix
          .l-left 販売手数料 (10%)
          .l-right#item_commission -
        %li.top_border.clearfix.bold
          .l-left 販売利益
          .l-right#item_profit -
  .sell-content.btn-box
    .btn-box__notes
      %p.btn-box__notes__note
        = link_to '禁止されている出品', '#'
        、
        = link_to '行為', '#'
        を必ずご確認ください。
      %p.btn-box__notes__note
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to '偽ブランドの販売','#'
        は犯罪であり処罰される可能性があります。
      %p.btn-box__notes__note
        また、出品をもちまして
        = link_to '加盟店規約', '#'
        に同意したことになります。
        
    - if (controller_path == 'item' && action_name == 'new')
      = f.submit "出品する", {class: "btn-box__default btn-box--red", id: "item-sell-submit-btn"}
      .btn-box__default.btn-box--gray もどる
    - else
      = f.submit "出品する", {class: "btn-box__default btn-box--red", id: "item-sell-submit-btn"}
      .btn-box__default.btn-box--gray もどる
      = link_to "", :back, id: "edit"

app/views/items/confirmation.html.haml
.sell-wrap
  %header.sell-header
    %h1
      = link_to root_path do
        = image_tag 'mercari_logo_color.svg', alt: 'mercari', height: '50px', width: '180px'
  %main.sell-main
    %section.sell-item-container
      %h2.single-head
        購入内容の確認
        = @item.name
      %section.sell-content.confirm
        .sell-content__inner.clearfix
          %h3.confirm__image
            = image_tag(@img.image.url, height: '60px', width: '60px')
          %p.confirm__name
            = @item.name
          = form_for(@item, url: confirmed_item_path(@item.id), class: "buy-form", method: :patch) do |f| 
            %p.confirm__price
              ￥
              = @item.price
              %span.item-shipping-fee 送料込み
            %ul.confirm__point
              %li.confirm__point--list
                ポイントはありません
            %ul.confirm__payment
              %li.confirm__payment-list
                .buy-price 支払金額
                .buy-price
                  %span
                    ￥
                    = @item.price
              = f.submit "購入する", {class: "btn--purchase"}
      %section.sell-content.buy-user__info
        .sell-content__inner
          %h3 配送先
          %address.buy-user__info--text
            〒
            = @detail.zip_code
            %br
            = @detail.address
            = @detail.building
            %br
            = @detail.first_name
            = @detail.family_name
          %p.buy-user__info--text
          = link_to "#", {class: 'buy-user__info--text--fix'} do
            %span 変更する
            %i.fa.fa-chevron-right
      %section.sell-content.buy-user__info{data: {buy: 'pay-method'}}
        .sell-content__inner
          %h3 支払方法
          %p.buy-user__info--text
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          = image_tag "credit-logo.svg", height: '20', width: '26'
          %p
          = link_to "#", {class: 'buy-user__info--text--fix'} do
            %span 変更する
            %i.fa.fa-chevron-right
  %footer.sell-footer
    %nav
      %ul.clearfix
        %li
          = link_to 'プライバシーポリシー', '#'
        %li
          = link_to 'メルカリ利用規約', '#'
        %li
          = link_to '特定商取引に関する表記', '#'
    = link_to "#", class: "sell-footer__logo" do
      = image_tag 'footer-logo-gray.svg', alt: 'mercari', height: '65', width: '80'
    %p
      %small ©︎ 2019 team0706a

app/views/items/confirmed.html.haml
.conf
  .box
    .box-inner
      %p.box-inner__text 商品の購入を完了しました！
      %p.box-inner__return
        = link_to "商品一覧へ戻る", root_path

app/views/items/edit.html.haml
.sell-wrap
  %header.sell-header
    %h1
      = link_to root_path do
        = image_tag 'mercari_logo_color.svg', alt: 'mercari', height: '50px', width: '180px'
  %main.sell-main
    %section.sell-item-container
      #sell-container
        .container__inner
          %h2.single-head
            商品の情報を編集
          = form_for @item, html: { class: "sell-form" } do |f|
            .upload-box{class: "#{'five' if @item.item_images.length >= 5}"}
              %h3.upload-box__head
                出品画像
                %span.form-require
                  必須
              %p
                最大10枚までアップロードできます
              .image-uproading.clearfix
                = f.fields_for @item.item_images do |image|
                  #new_images
                    - @item.item_images.each do |image|
                      .previewfield
                        = image_tag image.image_url.to_s, class: "itempreview", id:'id'
                        .up_view
                          .up_view__cover
                            = link_to "編集", "#", class: "up_edit"
                          = link_to "削除",  "#", class: "up_del"
                    .dropping#new_image{id: "#{@item.item_images.length >= 5? 'form_edit' : 'form'}"}
                      #new_image{onclick:"$('#new_file1').click()",data: {count: 1},id: "#{@item.item_images.length >= 5? 'form_edit' : 'form'}"} ドラッグアンドドロップ<br>またはクリックしてファイルをアップロード                  
                  = image.file_field :image,  multiple: true,id:"new_file1",name: "item_images[image][]",class:"new_file",style: "display:none"
            .sell-content
              .form-group
                = f.label :name do
                  商品名
                  %span.form-require 必須
                %div
                  = f.text_field :name, class: 'input-default input-default__width', placeholder: "商品名（必須 40文字まで)"
              .form-group
                = f.label :description do
                  商品の説明
                  %span.form-require 必須
                = f.text_area :description, class: 'textarea-default', size: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            .sell-content.clearfix
              %h3.sub-head 商品の詳細
              .form-box
                .form-group
                  = f.label :category_id do
                    カテゴリー
                    %span.form-require 必須
                  %div
                    .select-wrap
                      = f.select :category_id, [["レディース", "1"], ["メンズ", "2"], ["ベビー・キッズ","3"], ["インテリア・住まい・小物","4"], ["本・音楽・ゲーム","5"], ["おもちゃ・ホビー・グッズ","6"], ["コスメ・香水・美容","7"], ["家電・スマホ・カメラ","8"], ["スポーツ・レジャー","9"], ["ハンドメイド","10"], ["チケット","11"], ["自転車・オートバイ","12"], ["その他", "13"]], {prompt: "---"}, {class: 'select-default'}
                      %i.fa.fa-chevron-down.fa-lg
                .form-group
                  = f.label :state do
                    商品の状態
                    %span.form-require 必須
                  .select-wrap
                    = f.select :state, [["新品・未使用", "新品・未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"],], {prompt: "---"}, {class: "select-default"}
                    %i.fa.fa-chevron-down.fa-lg
            .sell-content.clearfix
              %h3.sub-head 配送について
              = link_to "#", class: "form-question" do
                %i.fa.fa-question-circle
              .form-box
                .form-group
                  = f.label :shipping_charges do
                    配送料の負担
                    %span.form-require 必須
                  %div
                    .select-wrap
                      = f.select :shipping_charges, [["送料込み(出品者負担)", "送料込み(出品者負担)"], ["着払い(購入者負担)", "着払い(購入者負担)"]], {prompt: "---"}, {class: 'select-default'}
                      %i.fa.fa-chevron-down.fa-lg
                .form-group
                  = f.label :shipping_method do
                    配送の方法
                    %span.form-require 必須
                  %div
                    .select-wrap
                      = f.select :shipping_method, [["未定", "未定"], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便(定型、定形外)", "普通郵便(定型、定形外)"], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["クリックポスト", "クリックポスト"], ["ゆうパケット", "ゆうパケット"]], {prompt: "---"}, {class: 'select-default'}
                      %i.fa.fa-chevron-down.fa-lg
                .form-group
                  = f.label :shipping_source_area do
                    発送元の地域
                    %span.form-require 必須
                  .select-wrap
                    = f.collection_select :shipping_source_area, Prefecture.all, :id, :name, {prompt: "---"}, {class: 'select-default'}
                    %i.fa.fa-chevron-down.fa-lg
                .form-group
                  = f.label :days_ship do
                    発送までの日数
                    %span.form-require 必須
                  .select-wrap
                    = f.select :days_ship, [["1~2日で発送", "1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]], {prompt: "---"}, {class: 'select-default'}
                    %i.fa.fa-chevron-down.fa-lg
            .sell-content.clearfix
              %h3.sub-head 販売価格(300〜9,999,999)
              = link_to "#", class: "form-question" do
                %i.fa.fa-question-circle
              .form-box
                %ul.price
                  %li.form-group
                    .clearfix
                      = f.label :price, class: "l-left" do
                        価格
                        %span.form-require 必須
                      .l-right.price-input
                        ¥
                        .price-input__container
                          = f.text_field :price, class: 'input-default', id: 'item_price', placeholder: "例）300"
                  %li.top_border.clearfix
                    .l-left 販売手数料 (10%)
                    .l-right#item_commission -
                  %li.top_border.clearfix.bold
                    .l-left 販売利益
                    .l-right#item_profit -
            .sell-content.btn-box
              .btn-box__notes
                %p.btn-box__notes__note
                  = link_to '禁止されている出品', '#'
                  、
                  = link_to '行為', '#'
                  を必ずご確認ください。
                %p.btn-box__notes__note
                  またブランド品でシリアルナンバー等がある場合はご記載ください。
                  = link_to '偽ブランドの販売','#'
                  は犯罪であり処罰される可能性があります。
                %p.btn-box__notes__note
                  また、出品をもちまして
                  = link_to '加盟店規約', '#'
                  に同意したことになります。
                  
              - if (controller_path == 'item' && action_name == 'new')
                = f.submit "出品する", {class: "btn-box__default btn-box--red", id: "item-sell-submit-btn"}
                .btn-box__default.btn-box--gray もどる
              - else
                = f.submit "出品する", {class: "btn-box__default btn-box--red", id: "item-sell-submit-btn"}
                .btn-box__default.btn-box--gray もどる
                = link_to "", :back, id: "edit"
          %footer.sell-footer
            %nav
              %ul.clearfix
                %li
                  = link_to 'プライバシーポリシー', '#'
                %li
                  = link_to 'メルカリ利用規約', '#'
                %li
                  = link_to '特定商取引に関する表記', '#'
            = link_to "#", class: "sell-footer__logo" do
              = image_tag 'footer-logo-gray.svg', alt: 'mercari', height: '65', width: '80'
            %p
              %small ©︎ 2019 team0706a

app/views/items/show.html.haml
.items-detail-wrap
  .item-name
    %h1 
    = @item.name

  .item-detail-content
    .item-detail-content__images
      .image-detail
        = image_tag(@item.item_images[0].image.url, width: '300', height: '300')
      .image-row
        .image-mini
          - @item.item_images.each do |img|
            = image_tag(img.image.url, width: '60', height: '60', class: 'mini-image')

    %table.item-detail-content__table
      %tr
        %th 出品者
        %td
          =link_to "#" do
            %p
            = @detail.user.nickname
          .rate
            .rate-good
              %i.fa.fa-star
              20
            .rate-normal
              %i.fa.fa-star-half
              10
            .rate-bad
              %i.fa.fa-star
              0
      %tr
        %th カテゴリー
        %td
          =link_to '#' do
            %span
            = @item.category.name 
            %br
            %i.fa.fa-chevron-right
            %span カテゴリ1
            %br
            %i.fa.fa-chevron-right
            %span カテゴリ2
      %tr
        %th ブランド
        %td
          =link_to '#' do
            %p その他
      %tr
        %th サイズ
        %td 
          = @item.size
      %tr
        %th 商品の状態
        %td 
          = @item.state
      %tr
        %th 配送料の負担
        %td
          = @item.delivery_status
      %tr
        %th 配送の方法
        %td
          = @item.shipping_method
      %tr
        %th 配送元地域
        %td
          =link_to '#' do
            %p
            = @item.shipping_source_area
      %tr
        %th 発送日の目安
        %td
          = @item.days_ship


  .item-detail-price
    %span.item-detail-price__taxed-price
      ¥ 
      = @item.price
    %span.item-detail-price__tax
      (税込)
    %span.item-detail-price__sum
      = @item.delivery_status

    
  - if @item.status == 'Sold' && user_signed_in? && current_user.id == @item.user_id then
    .item-close__btn
      = link_to root_path do
        %p 売り切れました
    .item-delete__btn
      = link_to item_path(@item.id), method: :delete do
        %p この商品を削除する
  - elsif @item.status == 'Sold' then
    .item-close__btn
      = link_to root_path do
        %p 売り切れました
  - else
    - if user_signed_in? && current_user.id == @item.user_id then
      .item-edit__btn
        = link_to edit_item_path(@item) do
          %p 商品の編集
      %p.text-center-or or
      .item-delete__btn
        = link_to item_path(@item.id), method: :delete do
          %p この商品を削除する
    - else
      .item-purchase__btn
        = link_to(confirmation_item_path(@item.id), class: 'buy-btn') do
          %p 購入画面に進む

  .item-detail-description
    %p
      = @item.description

  .item-btn-content
    .item-btn-content-left
      .item-btn-content__like
        %i.fa.fa-heart
        %span いいね! 5
      .item-btn-content__report
        = link_to '#', class: 'report-btn' do
          %i.fa.fa-flag
          %span 不適切な商品の報告

    .item-btn-content-right
      = link_to '#', class: 'report-btn' do
        %i.fa.fa-lock
        %span あんしん・あんぜんへの取り組み

.items-detail-message__box
  .items-detail-message__body.clearfix
    .items-message-content
    = image_tag('icon-image.png', class: 'user-face', width: '40', height: '40')
    .chatting
      .chats
        %p こんにちは
        .time
          %i.fa.fa-history
          %span 1日前

  .items-detail-message__body.clearfix
    .items-message-content
    = image_tag('icon-image.png', class: 'user-face', width: '40', height: '40')
    .chatting
      .chats
        %p こんにちは
        .time
          %i.fa.fa-history
          %span 2日前

  .items-message-head
    %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    = form_with do |f|
      = f.text_area :comment, type: 'input', class: 'message-head'
    .items-message-head__btn
      = link_to '#', class: 'messege-btn' do
        %span コメントする

%ul.item-link
  %li.item-link__prev
    =link_to '#' do
      %i.fa.fa-chevron-left
      %span サンダル ミュール パンプス 靴 春夏
  %li.item-link__next
    =link_to '#' do
      %span THE TEAM5つの法則
      %i.fa.fa-chevron-right

.social-medias
  %ul.social-media-box
    .facebook-box
      %li
        = link_to '#', class: 'facebook-icon' do
          %i.fa.fa-facebook-square
    .twitter-box
      %li
        = link_to '#', class: 'twitter-icon' do
          %i.fa.fa-twitter-square
    %li.pinterest-box
      = link_to '#', class: 'pinterest-icon' do
        %i.fa.fa-pinterest-square

.items-user-box
  %section.items-user-box__items
    %h4
      =link_to "#{@detail.user.nickname}"+"さんのその他の出品", "#"

    - @user_items.zip(@images) do |user_item, img|
      .items-user-box__items__row
        .items-user-box__items__row__listing
          =link_to '#' do
            = image_tag(img.image.url, width: '220', height: '220')
            .items-user-box__items__row__listing--body
              %h5
                = user_item.name
              .items-user-box__items__row__listing--body--price
                ¥
                = user_item.price
                %p (税込)