config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'signup/select' , to: 'signups#select'
  get 'signup/tel' , to: 'signups#tel'
  get 'signup/address' , to: 'signups#address'
  get 'signup/pay' , to: 'signups#pay'
  get 'signup/finish' , to: 'signups#finish'
  get '/logout', to: 'logout#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :users, only: [:show, :new]
  resources :top, only: [:index]
  resources :items, only: [:new, :create, :show, :update, :destroy]
  resources :purchases, only: [:index]
  resources :users, only: [:index]
  resources :cards, only: [:index, :new] do
    collection do
      get 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :items do
    member do
      get :confirmation
      patch :confirmed
    end
  end
  resources :profile, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many   :item_images, dependent: :destroy

  accepts_nested_attributes_for :item_images, allow_destroy: true

  validates :name,                       presence: true, length: {maximum: 40}
  validates :description,                presence: true, length: {maximum: 1000}
  validates :category_id,                numericality: {message: 'Please select'}
  validates :state,                      exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_charges,           exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_method,            exclusion: {in: %w(---), message: 'Please select'}
  validates :shipping_source_area,       exclusion: {in: %w(---), message: 'Please select'}
  validates :days_ship,                  exclusion: {in: %w(---), message: 'Please select'}
  validates :price,                      presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item, optional: true
end

app/models/items_category.rb
class ItemsCategory < ApplicationRecord
  has_many :items
end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: '北海道', name: '北海道'}, {id: '青森県', name: '青森県'}, {id: '岩手県', name: '岩手県'},
    {id: '宮城県', name: '宮城県'}, {id: '秋田県', name: '秋田県'}, {id: '山形県', name: '山形県'},
    {id: '福島県', name: '福島県'}, {id: '茨城県', name: '茨城県'}, {id: '栃木県', name: '栃木県'},
    {id: '群馬県', name: '群馬県'}, {id: '埼玉県', name: '埼玉県'}, {id: '千葉県', name: '千葉県'},
    {id: '東京都', name: '東京都'}, {id: '神奈川県', name: '神奈川県'}, {id: '新潟県', name: '新潟県'},
    {id: '富山県', name: '富山県'}, {id: '石川県', name: '石川県'}, {id: '福井県', name: '福井県'},
    {id: '山梨県', name: '山梨県'}, {id: '長野県', name: '長野県'}, {id: '岐阜県', name: '岐阜県'},
    {id: '静岡県', name: '静岡県'}, {id: '愛知県', name: '愛知県'}, {id: '三重県', name: '三重県'},
    {id: '滋賀県', name: '滋賀県'}, {id: '京都府', name: '京都府'}, {id: '大阪府', name: '大阪府'},
    {id: '兵庫県', name: '兵庫県'}, {id: '奈良県', name: '奈良県'}, {id: '和歌山県', name: '和歌山県'},
    {id: '鳥取県', name: '鳥取県'}, {id: '島根県', name: '島根県'}, {id: '岡山県', name: '岡山県'},
    {id: '広島県', name: '広島県'}, {id: '山口県', name: '山口県'}, {id: '徳島県', name: '徳島県'},
    {id: '香川県', name: '香川県'}, {id: '愛媛県', name: '愛媛県'}, {id: '高知県', name: '高知県'},
    {id: '福岡県', name: '福岡県'}, {id: '佐賀県', name: '佐賀県'}, {id: '長崎県', name: '長崎県'},
    {id: '熊本県', name: '熊本県'}, {id: '大分県', name: '大分県'}, {id: '宮崎県', name: '宮崎県'},
    {id: '鹿児島県', name: '鹿児島県'}, {id: '沖縄県', name: '沖縄県'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user

  validates :uid,      presence: true
  validates :provider, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  # アソシエーション
  has_many :items
  has_many :sns_credentials, dependent: :destroy
  has_one :user_detail
  has_one :card
  
  # バリデーション
  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password,                presence: true, length: {minimum: 6}
  # validates :password_confirmation,   presence: true, length: {minimum: 6}
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  def self.from_auth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
  has_one :point
end

app/models/users_valuation.rb
class UsersValuation < ApplicationRecord
end

app/models/valuation.rb
class Valuation < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require 'payjp'

  before_action :authenticate_user!, only: [:index, :new]
  before_action :card_info, only: [:delete, :show]
  layout "tab", only: [:index, :new, :show]

  def index
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = Rails.application.credentials.payjp[:secret]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    if @card.blank?
      redirect_to action: "new"
    else 
      Payjp.api_key = Rails.application.credentials.payjp[:secret]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      card.delete
    end
  end

  def show 
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def card_info
    @card = Card.where(user_id: current_user.id).first
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @wmen = searchItemImage(1)
    @men = searchItemImage(2)
    @kids = searchItemImage(3)
    @chans = searchItemImage(14)
    @louvs = searchItemImage(15)
    @nikes = searchItemImage(16)
  end

  def searchItemImage (category_id)
    items = Item.where(category_id: category_id)
    ItemImage.includes(:item).group(:item_id).where(item_id: items.ids).order('created_at DESC').limit(4)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cards/index.html.haml
= render 'layouts/breadcrumbs'

.mypage
  .mypage__main
    .contents
      .main
        = link_to '#', class: "fixed_btn" do
          出品
          %br/
          = fa_icon 'camera', class: 'icon'
        %h2 支払い方法
        .main-middle
          %p.one クレジットカード一覧
          = link_to '/cards/new' do
            %p.two
              = fa_icon 'credit-card', class: 'icon'
              クレジットカードを追加する
        %hr/
        %p.main-bottom
          = link_to '#' do
            支払い方法について
            %span
              = fa_icon 'chevron-right', class: 'icon'
  =render partial: "users/side_menu"

app/views/cards/new.html.haml
= render 'layouts/breadcrumbs'

.mypage
  .mypage__main
    .contents
      .main-two
        = link_to '#', class: 'fixed_btn' do
          出品
          %br/
          = fa_icon 'camera', class: 'icon'
        %h2 クレジットカード情報
        = form_tag(pay_cards_path, method: :post, class: 'payment-form', id: 'charge-form', name: "inputForm") do
          %label カード番号
          %p.mandatory 必須
          .input
            = text_field_tag "number", "", class: "input-default", placeholder: "半角英数のみ", maxlength: "16", type: "text", id: "card_number"
          .card-type.clearfix
            %ul
              %li.card-type__list
                = image_tag 'visa-credit.svg', class: 'visa'
              %li.card-type__list
                = image_tag 'master-card-credit.svg', class: 'master'
              %li.card-type__list
                = image_tag 'saison-card-credit.svg', class: 'saison'
              %li.card-type__list
                = image_tag 'jcb-credit.svg', class: 'jcb'
              %li.card-type__list
                = image_tag 'american_express-credit.svg', class: 'amex'
              %li.card-type__list
                = image_tag 'dinersclub-credit.svg', class: 'diners'
              %li.card-type__list
                = image_tag 'discover-credit.svg', class: 'discover'
          %label 有効期限

          %p.mandatory 必須
          .input
            %select#exp_month{name: "exp_month", type: "text", class: "select-default"}
              %option{value: ""} --
              %option{value: "1"} 01
              %option{value: "2"} 02
              %option{value: "3"} 03
              %option{value: "4"} 04
              %option{value: "5"} 05
              %option{value: "6"} 06
              %option{value: "7"} 07
              %option{value: "8"} 08
              %option{value: "9"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
              %option{value: "12"} 12
            %span 月/
            %select#exp_year{name: "exp_year", type: "text", class: "select-default"}
              %option{value: ""} --
              %option{value: "2019"} 19
              %option{value: "2020"} 20
              %option{value: "2021"} 21
              %option{value: "2022"} 22
              %option{value: "2023"} 23
              %option{value: "2024"} 24
              %option{value: "2025"} 25
              %option{value: "2026"} 26
              %option{value: "2027"} 27
              %option{value: "2028"} 28
              %option{value: "2029"} 29
            %span 年
          .security
            %label セキュリティコード
            %p.mandatory 必須
            .input
              = text_field_tag "cvc", "", class: "input-default", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
            %p.security-about
              %span.security-about__question ?
              カード裏面の番号とは？
          .form-submit.clearfix
            #card_token
            = submit_tag "追加する", class: "form-submit__btn", id: "token_submit"
  =render partial: "users/side_menu"

app/views/cards/show.html.haml
.mypage
  .mypage__main
    .contents
      .main
        = link_to '#', class: "fixed_btn" do
          出品
          %br/
          = fa_icon 'camera', class: 'icon'
        %h2 登録クレジットカード情報
        .main-middle
          %p.one
            カード番号
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            有効期限
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %br
            = image_tag "credit-logo.svg", height: '20', width: '26'
        %hr/
        %p.main-bottom
          = link_to '#' do
            支払い方法について
            %span
              = fa_icon 'chevron-right', class: 'icon'
  =render partial: "users/side_menu"

app/views/top/index.html.haml
.banner-top
  = image_tag('//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?2927923569', class: 'img_phone')
  .banner-text
    %p.line_one Free Market Apps
    %p.line_two Developed by Team 0706a
.main
  = link_to "/items/new", {class: 'fixed_btn'} do
    出品
    %br/
    = fa_icon 'camera', class: 'icon'

  %h1 ビックアップカテゴリー
  = link_to "#" do
    %h2 レディース新着アイテム
  .container.clearfix
    - @wmen.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do

          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')

          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good

  .container-bottom
    = link_to "#" do 
      すべての商品を見る

  = link_to "#" do
    %h2 メンズ新着アイテム
  .container.clearfix
    - @men.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do
          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')

          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good
  .container-bottom
    = link_to "#" do 
      すべての商品を見る

  = link_to "#" do
    %h2 ベビー・キッズ 新着アイテム
  .container.clearfix
    - @kids.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do
          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')
          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good
  .container-bottom
    = link_to "#" do 
      すべての商品を見る

  %h1 ビックアップブランド
  = link_to "#" do
    %h2 シャネル新着アイテム
  .container.clearfix
    - @chans.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do
          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')
          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good
  .container-bottom
    = link_to "#" do 
      すべての商品を見る

  = link_to "#" do
    %h2 ルイヴィトン新着アイテム
  .container.clearfix
    - @louvs.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do
          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')
          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good
  .container-bottom
    = link_to "#" do 
      すべての商品を見る

  = link_to "#" do
    %h2 ナイキ新着アイテム
  .container.clearfix
    - @nikes.each do |product|
      .container-cell
        = link_to(item_path(product.item.id)) do
          - if product.item.status == 'Sold'
            .status
              %p.sold SOLD
            = image_tag(product.image.url, class: 'container-cell__pix')
          - else
            = image_tag(product.image.url, class: 'container-cell__pix')
          .container-cell__description
            %ul
              %li.container-cell__description--product
                = product.item.name
              %li.container-cell__description--info
                %p.one
                  ￥#{product.item.price}
                %p.two
                  = fa_icon 'heart', class: 'icon'
                  = product.item.good
  .container-bottom
    = link_to "#" do 
      すべての商品を見る

.banner-bottom
  .banner-bottom__left.clearfix
    %p.text_01 スマホでかんたんフリマアプリ
    %p.text_02 今すぐ無料ダウンロード！
    .banner-bottom__left--bottom
      =image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2098311808',class: 'icon_01')
      =image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2098311808', class: 'icon_02')
      =image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2098311808', class: 'icon_03')
  =image_tag('//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?2927923569', class: 'img_phones')